[package]
name = "amethyst_core"
version = "0.10.1"
authors = ["Simon Rönnberg <seamonr@gmail.com>", "Joël Lupien <jojolepro@jojolepro.com>", "Amethyst Foundation <contact@amethyst.rs>"]
edition = "2018"
description = "Amethyst core"

documentation = "https://docs.amethyst.rs/stable/amethyst_core/"
homepage = "https://amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
amethyst_error = { path = "../amethyst_error", version = "0.5.0" }
approx = "0.3"
fnv = "1"
getset = "0.1"
legion = { version = "0.3", default-features = false, features = ["serialize", "crossbeam-events", "codegen"] }
log = "0.4"
nalgebra = { version = "0.22", features = ["serde-serialize"] }
num-traits = "0.2"
rayon = "1.4"
serde = { version = "1", features = ["derive"] }
shrev = "1"
shrinkwraprs = "0.3"
simba = "0.2"
smallvec = "1.4"
thread_profiler = { version = "0.3", optional = true }

[dev-dependencies]
#amethyst = { path = "..", version = "0.15.1" }
ron = "0.5.1"

[features]
profiler = ["thread_profiler/thread_profiler"]
parallel = ["legion/parallel"]
